script: |
        # 1. Entrar a la ruta raíz del proyecto (donde están src, public, etc.)
        cd /var/www/kryotec
        
        # 2. Actualizar el código desde GitHub
        git reset --hard HEAD
        git pull origin main
        
        # 3. Ejecutar el script de despliegue interno
        chmod +x deploy/deploy.sh
        bash deploy/deploy.sh
