# DESPLIEGUE EN HOSTINGER
      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            # Entramos a la carpeta base
            cd /var/www/kryotec/Kryotec_Cliente || cd /var/www/kryotec
            
            # Si estamos en la carpeta equivocada, entramos a la subcarpeta
            if [ -d "Kryotec_Cliente" ]; then cd Kryotec_Cliente; fi
            
            # Limpiamos cambios locales para evitar bloqueos del git pull
            git reset --hard HEAD
            git pull origin main
            
            # Ejecutamos el deploy
            chmod +x deploy/deploy.sh
            bash deploy/deploy.sh

      # DESPLIEGUE EN CONTABO
      - name: Deploy to Contabo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CONTABO_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /var/www/kryotec/Kryotec_Cliente || cd /var/www/kryotec
            if [ -d "Kryotec_Cliente" ]; then cd Kryotec_Cliente; fi
            git reset --hard HEAD
            git pull origin main
            chmod +x deploy/deploy.sh
            bash deploy/deploy.sh
