name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # DESPLIEGUE EN HOSTINGER
      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /var/www/kryotec/Kryotec_Cliente
            git reset --hard HEAD
            git pull origin main
            chmod +x deploy/deploy.sh
            bash deploy/deploy.sh

      # DESPLIEGUE EN CONTABO
      - name: Deploy to Contabo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CONTABO_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /var/www/kryotec/Kryotec_Cliente
            git reset --hard HEAD
            git pull origin main
            chmod +x deploy/deploy.sh
            bash deploy/deploy.sh
